spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/lesson4_db"
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
server:
  address: localhost
  port: 8081
